site: "Terraria: Otherworld - Русскоязычный сайт"
baseurl: "https://www.terraria-otherworld.ru"
description: "Русскоязычный сайт игры Terraria: Otherworld"
google_analytics: "UA-41002897-2"
disqus_shortname: terraria
paginate: 5
paginate_path: "/news:num/"

gems: [jekyll-paginate]

exclude: [ "config.rb", "CNAME", "README.md"]
