site: "Terraria: Otherworld - Русскоязычный сайт"
url: "https://www.terraria-otherworld.ru"
baseurl: "/"
description: "Русскоязычный сайт игры Terraria: Otherworld"
google_analytics: "UA-41002897-2"
disqus_shortname: terraria

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  
paginate: 5
paginate_path: "/news/page:num/"

exclude: [ "config.rb", "CNAME", "README.md", "Gemfile"]
